Some more Debian-related changes. It's not perfect yet, but getting close :)

diff --git a/caudium/trunk/debian/postinst b/caudium/trunk/debian/postinst
--- a/caudium/trunk/debian/postinst
+++ b/caudium/trunk/debian/postinst
@@ -23,6 +23,106 @@ set -e
 #     so that unnecessary prompting doesn't happen if a package's
 #     installation fails and the `postinst' is called with `abort-upgrade',
 #     `abort-remove' or `abort-deconfigure'.
+CAUDIUM_PIKE=/usr/lib/caudium/base_server/caudium.pike
+
+case "$1" in
+    configure)
+    set -x
+    db_get caudium/reconfig_localhost
+    if test "$RET" = "false"; then
+	db_stop
+	exit 0
+    fi
+    
+    db_get caudium/config_port
+    if test -n "$RET" -a "$RET" != "22202"; then
+        CONFIG_PORT="$RET"
+	$(sed -e "s/\(ConfigPorts.*\)\(22202\)\(.*\)/\1$RET\3/" $CAUDIUM_PIKE > $CAUDIUM_PIKE.new) \
+	  && mv $CAUDIUM_PIKE.new $CAUDIUM_PIKE
+    fi
+
+    db_get caudium/listen_on
+    if test -z "$RET"; then
+	LISTEN_IF="`hostname -f`"
+	PORTNO=80
+    else
+	LISTEN_IF="$RET"
+	PORTNO="`echo $RET | cut -s -d ':' -f 2`"
+        if test -z "$PORTNO"; then
+    	    PORTNO=80
+        else
+	    RET="`echo $RET | cut -s -d ':' -f 1`"
+	fi
+    fi
+    
+    CAUDIUM_IF="<a><str>$PORTNO</str><str>http</str><str>$RET</str><str></str></a>"
+    sed -e "s;@PLACEHOLDER@;$CAUDIUM_IF;" /etc/caudium/servers/localhost > \
+        /etc/caudium/servers/localhost.new && mv /etc/caudium/servers/localhost.new \
+	/etc/caudium/servers/localhost
+
+    db_get caudium/start_options
+    START_OPTIONS=
+
+    for o in `echo $RET | sed -e 's/,//g'`; do
+	case $o in
+	    threads) START_OPTIONS="$START_OPTIONS --with-threads" ;;
+	    debug) START_OPTIONS="$START_OPTIONS --with-debug" ;;
+	    once) START_OPTIONS="$START_OPTIONS --once" ;;
+	    profile) START_OPTIONS="$START_OPTIONS --with-profile" ;;
+	    fd-debug) START_OPTIONS="$START_OPTIONS --with-fd-debug" ;;
+	esac
+    done
+    if test -n "$START_OPTIONS"; then
+	echo $START_OPTIONS > /etc/caudium/start_options
+    fi
+    
+    db_stop
+    ;;
+
+    abort-upgrade|abort-remove|abort-deconfigure)
+    db_stop
+    db_purge
+    ;;
+
+    *)
+        echo "postinst called with unknown argument \`$1'" >&2
+        exit 0
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
+
+
+#! /bin/sh
+# postinst script for caudium
+#
+# see: dh_installdeb(1)
+
+set -e
+
+. /usr/share/debconf/confmodule
+
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see /usr/share/doc/packaging-manual/
+#
+# quoting from the policy:
+#     Any necessary prompting should almost always be confined to the
+#     post-installation script, and should be protected with a conditional
+#     so that unnecessary prompting doesn't happen if a package's
+#     installation fails and the `postinst' is called with `abort-upgrade',
+#     `abort-remove' or `abort-deconfigure'.
 
 case "$1" in
     configure)
